aiapps/aiapps/urls.py
from django.contrib import admin
from django.urls import path, include
# import ramen.views as ramen

app_name = 'ramen'
urlpatterns = [
    path('admin/', admin.site.urls),
    path('ramen/', include('ramen.urls')),
]

aiapps/ramen/urls.py
from django.urls import path
from . import views

app_name = 'ramen'
urlpatterns = [
    path('', views.index, name='index'),
    path('predict/', views.predict, name='predict'),
]

aiapps/ramen/models.py
from django.db import models

import numpy as np
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras.models import load_model
from PIL import Image
import io, base64
graph = tf.get_default_graph()

class Photo(models.Model):
    image = models.ImageField(upload_to='photos')

    IMAGE_SIZE = 224
    MODEL_FILE_PATH = './ramen/ml_models/ramen_VGG16_light.h5'
    # classes = ['ラーメン二郎 ひばりヶ丘駅前','ラーメン二郎 茨城守谷','ラーメン二郎 横浜関内','ラーメン二郎 荻窪','ラーメン二郎 歌舞伎町',    'ラーメン二郎 会津若松駅前',    'ラーメン二郎 環七一之江','ラーメン二郎 環七新代田',    'ラーメン二郎 亀戸',    'ラーメン二郎 京急川崎',    'ラーメン二郎 京成大久保',    'ラーメン二郎 桜台駅前',    'ラーメン二郎 札幌',    'ラーメン二郎 三田本',    'ラーメン二郎 小岩','ラーメン二郎 松戸駅前',    'ラーメン二郎 湘南藤沢',    'ラーメン二郎 上野毛',    'ラーメン二郎 新潟',    'ラーメン二郎 新宿小滝橋通り',    'ラーメン二郎 神田神保町',    'ラーメン二郎 西台駅前',  'ラーメン二郎 仙台','ラーメン二郎 千住大橋駅前',    'ラーメン二郎 相模大野',    'ラーメン二郎 池袋東口',    'ラーメン二郎 中山駅前',    'ラーメン二郎 栃木街道典',    'ラーメン二郎 八王子野猿街道2',    'ラーメン二郎 品川',    'ラーメン二郎 府中','ラーメン二郎 目黒',    'ラーメン二郎 立川']
    classes = [
      'めじろ台法政大学前',
      '亀戸',
      '京急川崎',
      '会津若松駅前',
      '横浜関内',
      '歌舞伎町',
      '環七一之江',
      '環七新代田',
      '茨城守谷',
      '荻窪',
      '京成大久保',
      '桜台駅前',
      '札幌',
      '三田本',
      '小岩',
      '松戸駅前',
      '湘南藤沢',
      '上野毛',
      '新潟',
      '新宿小滝橋通り'
      ]
    num_classes = len(classes)


    def predict(self):
        model = None
        global graph
        with graph.as_default():
            model = load_model(self.MODEL_FILE_PATH)
            
            img_data = self.image.read()
            img_bin = io.BytesIO(img_data)

            image = Image.open(img_bin)
            image = image.convert('RGB')
            image = image.resize((self.IMAGE_SIZE, self.IMAGE_SIZE))
            data = np.asarray(image)/255.0
            X = []
            X.append(data)
            X = np.array(X)

            result = model.predict([X])[0]
            predicted = result.argmax()
            percentage = int(result[predicted] * 100)

            # print(self.classes[predicted], percentage)
            return self.classes[predicted], percentage

aiapps/ramen/forms.py
from django import forms

class PhotoForm(forms.Form):
    image = forms.ImageField(widget=forms.FileInput(attrs={'class':'custom-file-input'}))

aiapps/ramen/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.template import loader
from .forms import PhotoForm
from .models import Photo

def index(request):
    template = loader.get_template('ramen/index.html')
    context = {'form':PhotoForm()}
    return HttpResponse(template.render(context, request))

def predict(request):
    if not request.method == 'POST':
        return
        redirect('ramen:index')
    
    form = PhotoForm(request.POST, request.FILES)
    if not form.is_valid():
        raise ValueError('Formが不正です')

    photo = Photo(image=form.cleaned_data['image'])
    predicted, percentage = photo.predict()
    
    template = loader.get_template('ramen/result.html')

    context = {
        'predicted':predicted,
        'percentage':percentage,
    }

    return HttpResponse(template.render(context, request))

aiapps/ramen/templates/ramen/base.html
<!DOCTYPE html>
<html lang="ja">
<head>
    <meta charset="UTF-8">
    {% load static %}
    {% load bootstrap4 %}
    {% bootstrap_css %}
    <link rel="stylesheet" type="text/css" href="{% static 'ramen/css/style.css' %}">
    {% bootstrap_javascript jquery='full' %}
    <titke>{% block title %}{% endblock %}</titke>
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand" href="#">画像判定アプリ</a>
    </nav>
    <div class="container">
        {% block content %}{% endblock %}
    </div>
</body>
</html>

aiapps/ramen/templates/ramen/index.html
{% extends 'ramen/base.html' %}
{% block title %}ラーメン推定アプリメニュー{% endblock %}

{% block content %}
<div>
    <h4 class="mt-4 mb-5 border-bottom"ラーメン推定アプリ></h4>
    <p>推定ボタンクリック</p>
    <form action="{% url 'ramen:predict' %}" method="post" class="form" enctype="multipart/form-data">
    {% csrf_token %}
    <div class="form-group">
        <div class="custom-file">
            {{ form.image }}
            <label class="custom-file-label" for="customFile">
                ファイルを選択してください。
            </label>
        </div>
    </div>
    <button type="submit" class="btn btn-primary">推定する</button>
    </form>
</div>
{% endblock %}

aiapps/ramen/templates/ramen/result.html
{% extends 'ramen/base.html' %}
{% block title %}ラーメン推定結果{% endblock %}

{% block content %}
<div>
    <h4 class="mt-4 mb-5 border-bottom"ラーメン推定結果></h4>

    <table class="="table>
        <tbody>
            <tr>
                <td>推定ラベル</td>
                <td>{{ predicted }}</td>
            </tr>
            <tr>
                <td>推定確立</td>
                <td>{{ percentage }}</td>
            </tr>
        </tbody>
    </table>

    <a href = "{% url 'ramen:index' %}" class="btn btn-primary">画像選択メニューに戻る</a>
</div>
{% endblock %}    